Repository NiklasRosenstein/bbplay, pull requests merged in 2019-12, with the labels that each got.

#3 fix incorrect route arguments in GET /api/v1/playlist/<playlist>
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: enhancement

#5 Add --cli and --exec options, add bbplay.server.__main__
  bbplay-server/src/bbplay/server/__main__.py
  bbplay-server/src/bbplay/server/app.py
  bbplay-server/src/bbplay/server/clients/youtube.py
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: feature

#7 udpate API formatting
  bbplay-server/API.md
Labels: enhancement

#8 Vote and veto API
  bbplay-server/API.md
  bbplay-server/scripts/test-round
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: enhancement

#13 Add scripts directory
  README.md
  bbplay-server/src/bbplay/server/app.py
  bbplay-server/src/bbplay/server/config/__init__.py
  scripts/install-nr-python-libs
  scripts/local-api-test
Labels: enhancement

#18 add missing PyYAML dependency, re-render setup.py
  bbplay-server/package.yaml
  bbplay-server/setup.py
Labels: backend, fix

#19 fix #17 -- registered users can now add any number of tracks
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: backend, fix

#23 Feature/progressbar
  app/src/components/Flex.tsx
  app/src/index.css
  app/src/pages/Playlist/EmbeddedPlayer.tsx
  app/src/pages/Playlist/FooterPlayer.tsx
  app/src/pages/Playlist/Playlist.tsx
  app/src/pages/Playlist/SongList.tsx
  app/src/pages/Playlist/YoutubeSearch.tsx
  app/src/service/youtube.ts
Labels: feature, frontend

#31 Fix put track
  bbplay-server/scripts/local-api-test
  bbplay-server/src/bbplay/framework/rest.py
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: backend, fix

#33 add back getAllTracks endpoint to not break current frontend app version
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: backend, fix

#37 Read forwarded for header
  bbplay-server/src/bbplay/server/models/playlist.py
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: backend, fix

#39 Read forwarded for
  bbplay-server/src/bbplay/server/models/playlist.py
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: backend, fix

#41 improve logging for X-Forwarded-For readout
  bbplay-server/src/bbplay/server/models/playlist.py
  bbplay-server/src/bbplay/server/views/api/v1/playlist.py
Labels: backend, enhancement

#43 disable video duration filtering, it requires too much YT Data Quota
  bbplay-server/src/bbplay/server/views/api/v1/youtube.py
Labels: backend, enhancement

#42 Set tracks to upnext
  app/src/pages/Playlist/SongCard.tsx
  app/src/pages/Playlist/SongList.tsx
  app/src/pages/Playlist/UpNext.tsx
  app/src/pages/Playlist/reducer.ts
Labels: feature, fix, frontend

#45 copy from public
  app/src/pages/Playlist/PublicPlaylist.tsx
  app/src/pages/Playlist/YoutubePaste.tsx
Labels: fix, frontend
